import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:reezolv/services/firebase_auth_service.dart';
import 'package:reezolv/services/firestore_service.dart';

/// Used to create user-dependant objects that need to be accessible by all widgets.
/// This widget should live above the [MaterialApp].
/// See [AuthWidget], a descendant widget that consumes the snapshot generated by this builder.
class AuthWidgetBuilder extends StatelessWidget {
  const AuthWidgetBuilder({Key key, @required this.builder}) : super(key: key);
  final Widget Function(BuildContext, AsyncSnapshot<FirebaseUser>) builder;

  @override
  Widget build(BuildContext context) {
    final authService =
        Provider.of<FirebaseAuthService>(context, listen: false);
    return StreamBuilder<FirebaseUser>(
      stream: authService.authStateChanged,
      builder: (context, snapshot) {
        final FirebaseUser user = snapshot.data;
        if (user != null) {
          return MultiProvider(
            providers: [
              Provider<FirebaseUser>(
                create: (_) => user,
              ),
              Provider<FirestoreService>(
                create: (_) => FirestoreService(uid: user.uid),
              )
            ],
            child: builder(context, snapshot),
          );
        }
        return builder(context, snapshot);
      },
    );
  }
}
